#source "http://ruby.taobao.org"
source "http://rubygems.org"

# Declare your gem's dependencies in rtheme.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
#gem "jquery-rails"

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger

#common used gem for all component
gem 'will_paginate', '~>3.0.2'
gem 'bootstrap-will_paginate', '~>0.0.7'
gem 'will_paginate_mongoid' , :git => 'http://github.com/grasp/will_paginate_mongoid.git'

gem "mongoid","~>3.0.6"

