require 'pathname'
source "http://rubygems.org"

# Declare your gem's dependencies in ruser.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails"

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'

gem "mongoid"

gem "rtheme" ,:path=>File.join(project_path,"Rtheme") #need change to gem path

group :development, :test do
    gem 'quiet_assets', :git => 'http://github.com/AgilionApps/quiet_assets'
end
