require 'pathname'
pn = Pathname.new(File.dirname(__FILE__))
project_path = pn.parent #do we have one line solution?

source "http://rubygems.org"

# Declare your gem's dependencies in ruser.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails" #seem could not delete here

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'


gem "settingslogic", "~> 2.0.6"

gem "will_paginate", "~> 3.0.3"
gem "will_paginate_mongoid", :git =>"http://github.com/grasp/will_paginate_mongoid.git"

#bootstrap resource needed?
group :assets do
    gem 'sass-rails',   '~> 3.2.5'
    gem 'coffee-rails', '~> 3.2.2'
    gem 'uglifier', '>= 1.2.4'
    gem 'bootstrap-sass', '~> 2.0.3.1'
end

gem "rtheme" ,:path=>File.join(project_path,"Rtheme") #need change to gem path
gem 'mongo'

group :development, :test do
    gem 'quiet_assets', :git => 'http://github.com/AgilionApps/quiet_assets'
    gem 'thin'
end
