# config/ruser.yml
defaults: &defaults
  app_name: "w090-ruser"
  google_analytics_key: "adfsdfdsfsd"

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
